[tool.poetry]
name = "unlearning"
version = "0.1.0"
description = ""
authors = ["TRDP CarolLeoNaty <lsbenitezpereira@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10"
vision-unlearning = "*"
python-dotenv = "~1.0"
mypy = "~1.12"
pycodestyle = "~2.12"
pytest-asyncio = "^0.24.0"

# Only needed for sparseperf
auto_gptq = "~0.7"
lm-eval = "*"
datasets = "*"
accelerate = "*"
sentencepiece = "*"
protobuf = "*"
optimum = {version = "*", optional = true, extras = ["--no-deps"]}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
